
import __ASTRO_IMAGE_IMPORT_OiUKJ from "./_images/post-007.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-007-happy-birthday.mdx";
import __ASTRO_IMAGE_IMPORT_Z1qz2GX from "./_images/post-001.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-001-ai-for-developers.mdx";
import __ASTRO_IMAGE_IMPORT_Z10IaxQ from "./_images/post-004.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-004-nostalgia-for-the-monolith.mdx";
import __ASTRO_IMAGE_IMPORT_Z2t0mki from "./_images/post-003.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-003-attention-to-detail.mdx";
import __ASTRO_IMAGE_IMPORT_Z29Q77U from "./_images/post-005.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-005-frostpunk.mdx";
import __ASTRO_IMAGE_IMPORT_1ftvyC from "./_images/post-008.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-008-meeting-anti-pattern.mdx";
import __ASTRO_IMAGE_IMPORT_Z29Xera from "./_images/post-002.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-002-titanic-risk-model.mdx";
import __ASTRO_IMAGE_IMPORT_L8osX from "./_images/post-006.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-006-culture-map.mdx";
import __ASTRO_IMAGE_IMPORT_ZF4lKy from "./_images/post-009.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-009-ai-pricing.mdx";
import __ASTRO_IMAGE_IMPORT_Z2fPVRg from "./_images/deadline-corgi/panel-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx";
import __ASTRO_IMAGE_IMPORT_2c8WBK from "./_images/deadline-corgi/panel-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx";
import __ASTRO_IMAGE_IMPORT_1yVIhP from "./_images/deadline-corgi/panel-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx";
import __ASTRO_IMAGE_IMPORT_VJtWU from "./_images/deadline-corgi/panel-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx";
export default new Map([["./_images/post-007.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-007-happy-birthday.mdx", __ASTRO_IMAGE_IMPORT_OiUKJ], ["./_images/post-001.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-001-ai-for-developers.mdx", __ASTRO_IMAGE_IMPORT_Z1qz2GX], ["./_images/post-004.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-004-nostalgia-for-the-monolith.mdx", __ASTRO_IMAGE_IMPORT_Z10IaxQ], ["./_images/post-003.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-003-attention-to-detail.mdx", __ASTRO_IMAGE_IMPORT_Z2t0mki], ["./_images/post-005.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-005-frostpunk.mdx", __ASTRO_IMAGE_IMPORT_Z29Q77U], ["./_images/post-008.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-008-meeting-anti-pattern.mdx", __ASTRO_IMAGE_IMPORT_1ftvyC], ["./_images/post-002.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-002-titanic-risk-model.mdx", __ASTRO_IMAGE_IMPORT_Z29Xera], ["./_images/post-006.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-006-culture-map.mdx", __ASTRO_IMAGE_IMPORT_L8osX], ["./_images/post-009.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fpost-009-ai-pricing.mdx", __ASTRO_IMAGE_IMPORT_ZF4lKy], ["./_images/deadline-corgi/panel-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx", __ASTRO_IMAGE_IMPORT_Z2fPVRg], ["./_images/deadline-corgi/panel-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx", __ASTRO_IMAGE_IMPORT_2c8WBK], ["./_images/deadline-corgi/panel-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx", __ASTRO_IMAGE_IMPORT_1yVIhP], ["./_images/deadline-corgi/panel-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fcomics%2Fdeadline-corgi.mdx", __ASTRO_IMAGE_IMPORT_VJtWU]]);
		